'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BloodBankStockTable
    Public Property BloodBankStockID As Integer
    Public Property BloodGroupID As Integer
    Public Property Status As Boolean
    Public Property Quantity As Integer
    Public Property Description As String
    Public Property BloodbankID As Integer

    Public Overridable Property BloodBankTable As BloodBankTable
    Public Overridable Property BloodGroupsTable As BloodGroupsTable

End Class
