'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BloodBankDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BloodBankDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AccountStatusTables() As DbSet(Of AccountStatusTable)
    Public Overridable Property BloodBankStockTables() As DbSet(Of BloodBankStockTable)
    Public Overridable Property BloodBankTables() As DbSet(Of BloodBankTable)
    Public Overridable Property BloodGroupsTables() As DbSet(Of BloodGroupsTable)
    Public Overridable Property CityTables() As DbSet(Of CityTable)
    Public Overridable Property DonarTables() As DbSet(Of DonarTable)
    Public Overridable Property HospitalTables() As DbSet(Of HospitalTable)
    Public Overridable Property RequestTables() As DbSet(Of RequestTable)
    Public Overridable Property RequestTypeTables() As DbSet(Of RequestTypeTable)
    Public Overridable Property UserTables() As DbSet(Of UserTable)
    Public Overridable Property UserTypeTables() As DbSet(Of UserTypeTable)

End Class
