'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BloodGroupsTable
    Public Property BloodGroupID As Integer
    Public Property BloodGroup As String

    Public Overridable Property BloodBankStockTables As ICollection(Of BloodBankStockTable) = New HashSet(Of BloodBankStockTable)
    Public Overridable Property DonarTables As ICollection(Of DonarTable) = New HashSet(Of DonarTable)

End Class
