'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CityTable
    Public Property CityID As Integer
    Public Property City As String

    Public Overridable Property BloodBankTables As ICollection(Of BloodBankTable) = New HashSet(Of BloodBankTable)
    Public Overridable Property DonarTables As ICollection(Of DonarTable) = New HashSet(Of DonarTable)
    Public Overridable Property HospitalTables As ICollection(Of HospitalTable) = New HashSet(Of HospitalTable)

End Class
