'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DonarTable
    Public Property DonorID As Integer
    Public Property FullName As String
    Public Property LastDonationdate As Date
    Public Property ContactNo As String
    Public Property CNIC As String
    Public Property Location As String
    Public Property CityID As Integer
    Public Property BloodGroupID As Integer
    Public Property UserID As Integer

    Public Overridable Property BloodGroupsTable As BloodGroupsTable
    Public Overridable Property CityTable As CityTable
    Public Overridable Property UserTable As UserTable

End Class
