'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HospitalTable
    Public Property HospitalID As Integer
    Public Property FullName As String
    Public Property Address As String
    Public Property PhoneNo As String
    Public Property Website As String
    Public Property Email As String
    Public Property Loaction As String
    Public Property CityID As Integer
    Public Property UserID As Integer

    Public Overridable Property CityTable As CityTable
    Public Overridable Property UserTable As UserTable

End Class
