'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RequestTable
    Public Property RequestID As Integer
    Public Property RequestDate As Date
    Public Property HospitalID As Integer
    Public Property BloodbankID As Integer
    Public Property DonarID As Integer
    Public Property RequiredBloodGroup As Integer
    Public Property RequestTypeID As Integer

    Public Overridable Property RequestTypeTable As RequestTypeTable

End Class
