'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RequestTypeTable
    Public Property RequestTypeID As Integer
    Public Property RequestType As String

    Public Overridable Property RequestTables As ICollection(Of RequestTable) = New HashSet(Of RequestTable)

End Class
