'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserTypeTable
    Public Property UserTypeID As Integer
    Public Property UserType As String

    Public Overridable Property UserTables As ICollection(Of UserTable) = New HashSet(Of UserTable)

End Class
