'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserTable
    Public Property UserID As Integer
    Public Property UserName As String
    Public Property Password As String
    Public Property EmailAddress As String
    Public Property AccountStatusID As Integer
    Public Property UserTypeID As Integer

    Public Overridable Property AccountStatusTable As AccountStatusTable
    Public Overridable Property BloodBankTables As ICollection(Of BloodBankTable) = New HashSet(Of BloodBankTable)
    Public Overridable Property BloodBankTables1 As ICollection(Of BloodBankTable) = New HashSet(Of BloodBankTable)
    Public Overridable Property DonarTables As ICollection(Of DonarTable) = New HashSet(Of DonarTable)
    Public Overridable Property HospitalTables As ICollection(Of HospitalTable) = New HashSet(Of HospitalTable)
    Public Overridable Property UserTypeTable As UserTypeTable

End Class
