//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTable
    {
        public int RequestID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int HospitalID { get; set; }
        public int BloodbankID { get; set; }
        public int DonarID { get; set; }
        public int RequiredBloodGroup { get; set; }
        public int RequestTypeID { get; set; }
    
        public virtual RequestTypeTable RequestTypeTable { get; set; }
    }
}
